/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DAO.AlunoDAO;
import Model.bean.Aluno;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Matheus
 */
public class AtualizarDados extends javax.swing.JFrame {

    /**
     * Creates new form AtualizarDados
     */
    public AtualizarDados() {
        initComponents();
        
          DefaultTableModel modelo = (DefaultTableModel) jTableAtualizarDados.getModel();
        jTableAtualizarDados.setRowSorter(new TableRowSorter(modelo));

        readJTable();
        
         setLocationRelativeTo( null ); /* esta linha centraliza a janela*/
    }
    
    public void readJTable(){
        
        DefaultTableModel modelo = (DefaultTableModel) jTableAtualizarDados.getModel();
          modelo.setNumRows(0);
        AlunoDAO aDAO = new AlunoDAO();
        
        for(Aluno a: aDAO.read()){
            
           modelo.addRow(new Object[]{
               a.getMatricula(),
               a.getNome(),
               a.getEndereco(),
               a.getNomeDaMae(),
               a.getNomeDoPai(),
               a.getCelular(),
               a.getCpf()
           });
        }
        
    }
    
    public void readNome(String nome){
        
        DefaultTableModel modelo = (DefaultTableModel) jTableAtualizarDados.getModel();
          modelo.setNumRows(0);
        AlunoDAO aDAO = new AlunoDAO();
        
        for(Aluno a: aDAO.read()){
            
           modelo.addRow(new Object[]{
               a.getMatricula(),
               a.getNome(),
               a.getEndereco(),
               a.getNomeDaMae(),
               a.getNomeDoPai(),
               a.getCelular(),
               a.getCpf()
           });
        }
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNomeDaMae = new javax.swing.JTextField();
        txtNomeDoPai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAtualizarDados = new javax.swing.JTable();
        txtCelular = new javax.swing.JFormattedTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(756, 792));
        setPreferredSize(new java.awt.Dimension(755, 821));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 760, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1178, 1154, -1, -1));

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 329, 31));

        jLabel2.setText("Nome da Mãe");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel3.setText("Nome do Pai");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 329, 31));

        jLabel4.setText("Endereço");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 329, 31));

        jLabel5.setText("Tel. Contato");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        txtNomeDaMae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeDaMaeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeDaMae, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 329, 31));

        txtNomeDoPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeDoPaiActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeDoPai, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 329, 31));

        jLabel6.setText("CPF:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        jLabel7.setText("Senha");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        jLabel8.setText("Login");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 329, 31));

        btnLimpar.setText("Limpar campos");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 120, -1));

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 120, -1));

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 120, -1));

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 121, -1));

        jTableAtualizarDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nome", " Endereco", "Nome da Mãe", "Nome do Pai ", "Celular ", "CPF"
            }
        ));
        jTableAtualizarDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAtualizarDadosMouseClicked(evt);
            }
        });
        jTableAtualizarDados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableAtualizarDadosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAtualizarDados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 700, 270));

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 329, 31));

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 329, 31));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/view Atualizar Dados.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void txtNomeDaMaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeDaMaeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeDaMaeActionPerformed

    private void txtNomeDoPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeDoPaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeDoPaiActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
      dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
       // readNome(txtNome.getText());
           txtNome.setText("");
           txtEndereco.setText("");
           txtNomeDaMae.setText("");
           txtNomeDoPai.setText("");
           txtCelular.setText("");
           txtCpf.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // System.out.println("Linha selecionada: "+jTableAtualizarDados.getSelectedRow());
        
        if (jTableAtualizarDados.getSelectedRow() != -1) {

            Aluno a = new Aluno();
          AlunoDAO aDAO = new AlunoDAO();

            a.setId((int) jTableAtualizarDados.getValueAt(jTableAtualizarDados.getSelectedRow(), 0));
            
            aDAO.delete(a);
            //Limpando campo
           txtNome.setText("");
           txtEndereco.setText("");
           txtNomeDaMae.setText("");
           txtNomeDoPai.setText("");
           txtCelular.setText("");
           txtCpf.setText("");
           
            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Aluno para excluir.");
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void jTableAtualizarDadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableAtualizarDadosKeyReleased
      if (jTableAtualizarDados.getSelectedRow() != -1) {

            txtNome.setText(jTableAtualizarDados.getValueAt(jTableAtualizarDados.getSelectedRow(), 1).toString());
            txtEndereco.setText(jTableAtualizarDados.getValueAt(jTableAtualizarDados.getSelectedRow(), 2).toString());
            txtNomeDaMae.setText(jTableAtualizarDados.getValueAt(jTableAtualizarDados.getSelectedRow(), 3).toString());
            txtNomeDoPai.setText(jTableAtualizarDados.getValueAt(jTableAtualizarDados.getSelectedRow(), 4).toString());
            txtCelular.setText(jTableAtualizarDados.getValueAt(jTableAtualizarDados.getSelectedRow(), 5).toString());
            txtCpf.setText(jTableAtualizarDados.getValueAt(jTableAtualizarDados.getSelectedRow(), 6).toString());

        }
    }//GEN-LAST:event_jTableAtualizarDadosKeyReleased

    private void jTableAtualizarDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAtualizarDadosMouseClicked
         if (jTableAtualizarDados.getSelectedRow() != -1) {

            txtNome.setText(jTableAtualizarDados.getValueAt(jTableAtualizarDados.getSelectedRow(), 1).toString());
            txtEndereco.setText(jTableAtualizarDados.getValueAt(jTableAtualizarDados.getSelectedRow(), 2).toString());
            txtNomeDaMae.setText(jTableAtualizarDados.getValueAt(jTableAtualizarDados.getSelectedRow(), 3).toString());
            txtNomeDoPai.setText(jTableAtualizarDados.getValueAt(jTableAtualizarDados.getSelectedRow(), 4).toString());
            txtCelular.setText(jTableAtualizarDados.getValueAt(jTableAtualizarDados.getSelectedRow(), 5).toString());
            txtCpf.setText(jTableAtualizarDados.getValueAt(jTableAtualizarDados.getSelectedRow(), 6).toString());

        }
    }//GEN-LAST:event_jTableAtualizarDadosMouseClicked

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        if (jTableAtualizarDados.getSelectedRow() != -1) {

            Aluno a = new Aluno();
          AlunoDAO aDAO = new AlunoDAO();

            a.setId((int) jTableAtualizarDados.getValueAt(jTableAtualizarDados.getSelectedRow(), 0));
            a.setNome(txtNome.getText());
            a.setEndereco(txtEndereco.getText());
            a.setNomeDaMae(txtNomeDaMae.getText());
            a.setNomeDoPai(txtNomeDoPai.getText());
            a.setCelular(txtCelular.getText());
            a.setCpf(txtCpf.getText());
            
            aDAO.Atualizar(a);
            //Limpando campo
           txtNome.setText("");
           txtEndereco.setText("");
           txtNomeDaMae.setText("");
           txtNomeDoPai.setText("");
           txtCelular.setText("");
           txtCpf.setText("");
           
           readJTable();

        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtualizarDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAtualizarDados;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeDaMae;
    private javax.swing.JTextField txtNomeDoPai;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
