/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Matheus
 */
public class MenuProfessor extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MenuProfessor() {
        initComponents();
        setLocationRelativeTo( null ); /* esta linha centraliza a janela*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtualizar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnCadastar = new javax.swing.JButton();
        btnLancarNota_Frec = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("ATUALIZA/EDITAR DADOS");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 200, 40));

        btnSair.setBackground(new java.awt.Color(255, 255, 255));
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 200, 40));

        btnCadastar.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastar.setText("CADASTRAR NOVO ALUNO");
        btnCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 200, 40));

        btnLancarNota_Frec.setBackground(new java.awt.Color(255, 255, 255));
        btnLancarNota_Frec.setText("LANÇAR NOTA/FREQUÊNCIA");
        btnLancarNota_Frec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancarNota_FrecActionPerformed(evt);
            }
        });
        getContentPane().add(btnLancarNota_Frec, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 200, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fundo menu professor.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        AtualizarDados tela = new AtualizarDados();
        tela.setVisible(true);
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnCadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastarActionPerformed
        // este comandos são responsaveis por invocar a tela de cadastro de alunos 
        CadastroAluno tela = new CadastroAluno();
            tela.setVisible(true);
    }//GEN-LAST:event_btnCadastarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       
        dispose(); /*Esta linha fecha a janela */
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnLancarNota_FrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancarNota_FrecActionPerformed
        // TODO add your handling code here:
        
        TelaLancarNotas_Freq tela = new TelaLancarNotas_Freq();
        tela.setVisible(true);
    }//GEN-LAST:event_btnLancarNota_FrecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastar;
    private javax.swing.JButton btnLancarNota_Frec;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
